### ISSUE TITLE
Is this still work ?

### ISSUE THREAD

**Issue by yanchespenda** [StirlingMarketingGroup/mysql-http#2]
I just tried in mysql 8.0 community in centos 8

I installed
go 1.18
mysql-devel

and build successfull, but I'am test with `select 'http_touch'();` it return `ERROR 1123 (HY000): Can't initialize function 'http_touch'; 'http_touch' requires 1 parameter: the URL string`

Second test, with `select'http_touch'('http://192.168.168.122:8007/api/public/ok');`
it return 
```
+-----------------------------------------------------------+
| `http_touch`('http://192.168.168.122:8007/api/public/ok') |
+-----------------------------------------------------------+
|                                                      NULL |
+-----------------------------------------------------------+
```
The request not calling from the url, how to fix it ? thanks :)

**Comment by BrianLeishman** [comment]
`NULL` is the correct response for this. `http_touch` only makes a request, but doesn't wait for the response. You should be able to see the call being made from your server log
